### ISSUE TITLE
Add ligature for Khah and Yeh at the and of word

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [alif-type/amiri#148]
Seen from the website, I found Khah and Yeh should become ligature for presented joining, compare with Ain-Yeh ligature.
![Look at red boxes](https://user-images.githubusercontent.com/10364351/37981127-5b3f7bc2-321f-11e8-9035-64871f07e08c.PNG)

**Comment by KrasnayaPloshchad** [comment]
It seems to me that you have already implemented.
![Look!](https://i.imgur.com/j3kGDQu.png)
But it appears only in individual cases, not at the and of word.

**Comment by khaledhosny** [comment]
Duplicate of #180
