### ISSUE TITLE
الحروف التي لها سنة في آخرها لا ينضبط تلوينها في بعض التراكيب

### ISSUE THREAD

**Issue by hubaishan** [alif-type/amiri#194]
من المميزات المهمة للخط الأميري إمكانية تلوين الحروف ولو كانت متراكبة مع حروف أخرى مما يفيد في عملية التعليم وخاصة في دروس التجويد وتعليم الحروف، لكن الحروف ( س، ش، ص، ض) في بعض التراكيب تلون سنتها الأخيرة مع الحرف التالي لها، فلو  تلون السنة الأخيرة مع هذه الحروف يكون أكمل في عملية التعليم بالتلوين
في الصورة أحرف أخرى ملونة على الصواب في نفس التراكيب
![image](https://user-images.githubusercontent.com/2285457/86516095-7f2e5900-be26-11ea-93d3-e098be22dc4d.png)

**Comment by khaledhosny** [comment]
<div dir="rtl">
هذا يرجع إلى كيفية تكوين هذه التراكيب في ملف الخط، فالسين والصاد يعاد استخدام نفس الشكل مع الياء المنتهية (لتقليل عدد الأشكال في الخط، وعددها حاليا وصل أكثر من ستة آلاف). نفس الشكل للسين والصاد مستخدم في:

![a](https://user-images.githubusercontent.com/93914/91641371-29d88780-ea24-11ea-99c0-0e41f2e0247a.png)

إصلاح مشكلة التلوين سيتطلب إضافة ٣٦×٤ أشكال جديدة.
