### ISSUE TITLE
تركيب الميم بعد التاء

### ISSUE THREAD

**Issue by munzirtaha** [alif-type/amiri#88]
تركيب الميم بعد التاء أو الياء في الخط الأميري قرآن يخالف ما عليه المصحف الأميري وكذلك مصحف المدينة النبوية ويؤثر في جمالية بعض التراكيب مثلا كلمة اعتزلتموهم في سورة الكهف صارت فيها اللام صغيرة بصورة لم ترق لي وهذا ما دفعني لمراجعتها في المصحفين

![16](https://cloud.githubusercontent.com/assets/2936425/16529068/5fc5bde0-3fc9-11e6-83f2-288f6209275c.jpg)

**Comment by munzirtaha** [comment]
Thanks. But I think the Amiri version Lam needs to be taller. Like
![default](https://user-images.githubusercontent.com/2936425/33914986-e6666b90-dfb1-11e7-8ec1-4e9e1500e310.png)

**Comment by khaledhosny** [comment]
The lam is intentionally short in Amiri (and Bulaq) to avoid having too tall letters in the line, which does not work very well for typesetting (as compared to calligraphers who can balance things visually).

**Comment by munzirtaha** [comment]
Can you please attach an example where lam is intentionally short in Bulaq Mushaf?

**Comment by khaledhosny** [comment]
Here is the full Bulaq typecase:
![tif007-mod2](https://user-images.githubusercontent.com/93914/33937057-903e3d5c-e00a-11e7-993e-abbe52749293.jpg)

**Comment by munzirtaha** [comment]
Thanks for sharing.
