### ISSUE TITLE
شكل النبرة بعد الكاف مختلف

### ISSUE THREAD

**Issue by munzirtaha** [alif-type/amiri#92]
كلمة 
![correct](https://cloud.githubusercontent.com/assets/2936425/16560292/245b7d24-41fb-11e6-8e3f-d22b344b29f2.jpeg) رسمت 
![wrong](https://cloud.githubusercontent.com/assets/2936425/16560300/2d69eb9e-41fb-11e6-96bd-769355144013.jpeg) بصورة مختلفة وأقل وضوحا وجمالا عنها في أصل المصحف

**Comment by khaledhosny** [comment]
في رأيي أن نسخة الخط الأميري أجمل، و أظن أن سبب عدم استخدام هذا التركيب في المصحف أنه لم يرد إلا مرة واحدة في المصحف كله و لم يتوفر قالب رصاص له، و إلا فأنه مستخدم مع حروف أخرى من نفس المجموعة:
![image](https://user-images.githubusercontent.com/93914/33903196-354d6f2e-df80-11e7-9a76-538b94b5a5e4.png)
![image](https://user-images.githubusercontent.com/93914/33903257-806d5c58-df80-11e7-990f-79b8eff0a26b.png)
